export const ROLES = {
  VIEWER: "VIEWER",
  WORKER: "WORKER",
  ADMIN: "ADMIN",
};

export const EXPENSE_CATEGORIES = {
  STAFF_PAYMENT: "STAFF_PAYMENT",
  SUPPLIES: "SUPPLIES",
  OTHER: "OTHER",
};

export const EXPENSE_LABELS = {
  [EXPENSE_CATEGORIES.STAFF_PAYMENT]: "Pago de Staff",
  [EXPENSE_CATEGORIES.SUPPLIES]: "Suministros",
  [EXPENSE_CATEGORIES.OTHER]: "Otros",
};

export const DEBT_STATUS = {
  PENDING: "PENDING",
  PAID: "PAID",
  CANCELLED: "CANCELLED",
};

export const PAYMENT_METHODS = {
  CASH: "CASH",
  YAPE: "YAPE",
};

export const PAYMENT_METHOD_LABELS = {
  [PAYMENT_METHODS.CASH]: "Efectivo",
  [PAYMENT_METHODS.YAPE]: "Yape",
};
